#!/bin/bash

IFS=$'\n'
for LINE in $(w -hs) ; do
	USER="$(echo "$LINE" | awk '{print $1}')"
	USER_ID="$(id -u "$USER")"
	sudo -u "$USER" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$USER_ID/bus" \
		notify-send -u critical -a "S.M.A.R.T. Error" "Type: $SMARTD_FAILTYPE" "$SMARTD_MESSAGE" --icon=dialog-warning
done
