#!/bin/bash

create_snapshot() {
    local dataset="${1}"
    local snapshot_name="${2}"

    echo "==> Creating snapshot: ${dataset}@${snapshot_name}"

    if ! zfs snapshot "${dataset}@${snapshot_name}" ; then
        echo "==> ERROR: Could not create snapshot!"
        return 1
    fi
}

# Prune snapshots, keeping the last n.
prune_snapshots() {
    local dataset="${1}"
    local keep="${2}"

    echo "==> Pruning snapshots"
    if ! zfs list -H -t snapshot -o name "${dataset}" | head -n "-${keep}" | sudo xargs -r -n 1 zfs destroy ; then
        return 1
    fi
}

main() {
    local bootfs
    bootfs="$(zpool get bootfs -o value -pH zroot)" || return 1
    if [[ -z ${bootfs} ]] ; then
        echo "==> ERROR: Could not determine root dataset!"
        return 1
    fi

    create_snapshot "$bootfs" "pacman-$(date +%s)" || return 1
    prune_snapshots "$bootfs" 10 || return 1

    echo "==> Done!"
}

if ! main ; then
    exit 1
fi
