---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine latest semver tag
        id: get_tag
        run: |
          latest_tag="$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' | sort -V | tail -n 1)"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Checkout latest chronological tag
        run: git checkout "${{ env.latest_tag }}"

      - name: Build ISO image
        uses: ./.github/actions/build
        with:
          artifact_name: arch-grit

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: arch-grit

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*'
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          removeArtifacts: true
          tag: ${{ needs.build.outputs.latest_tag }}
